#! /bin/sh

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server
# Description:       starts nginx using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/nginx
NAME=nginx

# Include nginx defaults if available
if [ -f /etc/default/nginx ] ; then
    . /etc/default/nginx
fi

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting" "${NAME}"
    start-stop-daemon --start --oknodo --quiet --pidfile "/var/run/${NAME}.pid" --exec "${DAEMON}" -- ${DAEMON_OPTS} && log_end_msg 0 || log_end_msg 1
    ;;
  stop)
    log_daemon_msg "Stopping" "${NAME}"
    start-stop-daemon --stop --oknodo --quiet --pidfile "/var/run/${NAME}.pid" --exec "${DAEMON}" && log_end_msg 0 || log_end_msg 1
    ;;
  restart|force-reload)
    log_daemon_msg "Restarting" "${NAME}"
    (
      start-stop-daemon --stop --retry 1 --oknodo --quiet --pidfile "/var/run/${NAME}.pid" --exec "${DAEMON}" &&
      start-stop-daemon --start --quiet --pidfile "/var/run/${NAME}.pid" --exec "${DAEMON}" -- ${DAEMON_OPTS}
    ) && log_end_msg 0 || log_end_msg 1
    ;;
  reload)
    log_daemon_msg "Reloading" "${NAME}"
    start-stop-daemon --stop --signal HUP --quiet --pidfile "/var/run/${NAME}.pid" --exec "${DAEMON}" && log_end_msg 0 || log_end_msg 1
    ;;
  status)
    status_of_proc -p "/var/run/${NAME}.pid" "${DAEMON}" nginx && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0
