#!/bin/sh
### BEGIN INIT INFO
# Provides:          monit
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: service and resource monitoring daemon
### END INIT INFO
# /etc/init.d/monit start and stop monit daemon monitor process.
# Fredrik Steen, stone@debian.org
# Stefan Alfredsson, alfs@debian.org

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/monit
NAME=monit
DESC="daemon monitor"

set -e

. /lib/lsb/init-functions

# Check if DAEMON binary exist
test -f $DAEMON || exit 0

if [ -f "/etc/default/${NAME}" ]; then
     . "/etc/default/${NAME}"
fi

if [ ! -d /var/lib/monit ]; then
    mkdir -p /var/lib/monit
fi

ARGS="-s /var/lib/monit/monit.state"

monit_not_configured () {
    printf "%b\n" "monit won't be started/stopped\n\tunless it it's configured"
    if [ "$1" != "stop" ]
        then
        printf "%b\n" "\tplease configure monit and then edit /etc/default/monit"
        printf "%b\n" "\tand set the \"startup\" variable to 1 in order to allow "
        printf "%b\n" "\tmonit to start"
    fi
    exit 0
}

monit_check_syntax () {
  $DAEMON -t;
}


monit_checks () {
    # Check if startup variable is set to 1, if not we exit.
    if [ "$startup" != "1" ]; then
        monit_not_configured $1
    fi
}

case "$1" in
  start)
    echo -n "Starting $DESC: "
    monit_checks $1
    echo -n "$NAME"
    start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON > /dev/null 2>&1 -- $ARGS
    echo "."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    #monit_checks $1
    echo -n "$NAME"
    start-stop-daemon --retry 5 --oknodo --stop --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON
    echo "."
    ;;
  status)
    status_of_proc -p /var/run/${NAME}.pid "${DAEMON}" "${NAME}" && exit 0
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  syntax)
   monit_check_syntax
   ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|status|restart|force-reload|syntax}" >&2
    exit 1
    ;;
esac

exit 0
