#! /bin/sh

### BEGIN INIT INFO
# Provides:          collectd
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the collectd stats server
# Description:       starts collectd using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=collectd
DESC=collectd
PIDFILE=/var/run/collectd/${NAME}.pid
DAEMON=/usr/sbin/collectd
DAEMON_OPTS="-f"

test -x $DAEMON || exit 0

# Include collectd defaults if available
if [ -f /etc/default/collectd ] ; then
    . /etc/default/collectd
fi

set -e

. /lib/lsb/init-functions

if [ ! -d /var/run/collectd ]; then
    mkdir -p /var/run/collectd
    chown collectd:collectd /var/run/collectd
fi

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon --start --background --make-pidfile --quiet --pidfile "${PIDFILE}" --chuid collectd --name "${NAME}" --startas "${DAEMON}" -- "${DAEMON_OPTS}" || true
    echo "${NAME}."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon --stop --quiet --pidfile "${PIDFILE}" --name "${NAME}" || true
    echo "${NAME}."
    ;;
  restart|force-reload|reload)
    echo -n "Restarting $DESC: "
    start-stop-daemon --stop --quiet --pidfile "${PIDFILE}" --name "${NAME}" || true
    sleep 1
    start-stop-daemon --start --background --make-pidfile --quiet --pidfile "${PIDFILE}" --chuid collectd  --name "${NAME}" --startas "${DAEMON}" -- "${DAEMON_OPTS}" || true
    echo "${NAME}."
    ;;
  status)
    status_of_proc -p "${PIDFILE}" "$DAEMON" "${NAME}" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|force-reload|reload|status}" >&2
    exit 1
    ;;
esac

exit 0
