#!/bin/sh

set -e

case "$1" in
    configure)
        if [ ! `id -u haproxy 2>/dev/null` ]; then
            adduser --quiet --system --disabled-password --disabled-login --home /var/lib/haproxy \
                    --no-create-home --force-badname --group haproxy
        fi
        ;;
esac

#DEBHELPER#

exit 0
